### ISSUE TITLE
ruby 2.6.0 

### ISSUE THREAD

**Issue by HolyWalley** [LendingHome/pipe_operator#2]
in ruby 2.6.0

`(JSON.method(:parse) << Net::HTTP.method(:get) << URI.method(:parse)).call('https://jsonplaceholder.typicode.com/todos/1')`

https://bugs.ruby-lang.org/issues/6284

**Comment by shuber** [comment]
That Ruby issue ticket is one of the reasons this gem exists! 
https://github.com/LendingHome/pipe_operator#why
